### ISSUE TITLE
Need for dark mode in this application.

### ISSUE THREAD

**Issue by sohelajani** [zaidajani/textutils#1]
Nowadays, dark mode is very essential and improves the user experience.  Therefore, It is my suggestion to implement dark mode in this application in order to make it more user-friendly.

**Comment by zaidajani** [comment]
Hi @sohelajani,

Thanks for your great suggestion. It will surely help users interact more with the page and will improvise user experience by a huge number. I will close this comment tomorrow incorporating your suggestion and once reminding you about it.

Regards,
Zaid

**Comment by zaidajani** [comment]
Dark mode added!
